// ─────────────────────────────────────────────────────────────────────────────
// services/jsonService.js
// Generic JSON data fetcher with in-memory cache and fallback strategy.
// All data fetching in the app goes through here — never fetch() directly.
// ─────────────────────────────────────────────────────────────────────────────

// Simple in-memory cache: { [url]: { data, fetchedAt } }
const cache = {};

// How long a cached response stays valid (5 minutes)   
const CACHE_TTL_MS = 5 * 60 * 1000;

/**
 * Fetch a JSON file. Returns cached result if still fresh.
 *
 * @param {string} url         - Path or URL to the JSON file
 * @param {object} [fallback]  - Value to return if fetch fails (default: null)
 * @returns {Promise<any>}
 */
export async function fetchJson(url, fallback = null) {
  // ── Return from cache if fresh ──────────────────────────────────────────
  const cached = cache[url];
  const now = Date.now();

  if (cached && now - cached.fetchedAt < CACHE_TTL_MS) {
    return cached.data;
  }

  // ── Fetch from network ───────────────────────────────────────────────────
  try {
    const response = await fetch(url);

    if (!response.ok) {
      throw new Error(`HTTP ${response.status} for ${url}`);
    }

    const data = await response.json();

    // Store in cache
    cache[url] = { data, fetchedAt: now };

    return data;
  } catch (error) {
    // ── Fallback strategy ──────────────────────────────────────────────────
    // 1. Return stale cache if available (better than nothing)
    if (cached) {
      return cached.data;
    }

    // 2. Return provided fallback value
    return fallback;
  }
}

/**
 * Force-clear a specific URL from cache (useful after a manual sync).
 * @param {string} url
 */
export function invalidateCache(url) {
  delete cache[url];
}

/**
 * Clear all cached entries.
 */
export function clearAllCache() {
  Object.keys(cache).forEach(key => delete cache[key]);
}

// ── Convenience helpers ───────────────────────────────────────────────────────

import { SITE } from "../config/site.js";

/**
 * Fetch the episodes list from the local JSON file generated by youtube-fetch.js
 * @returns {Promise<Array>} Array of episode objects, or [] on failure
 */
export function fetchEpisodes() {
  console.log(`[jsonService] Fetching episodes from ${SITE.episodesDataPath}`);
  return fetchJson(SITE.episodesDataPath, []);
}

/**
 * Fetch the products list
 * @returns {Promise<Array>} Array of product objects, or [] on failure
 */
export function fetchProducts() {
  return fetchJson(SITE.productsDataPath, []);
}